export const INIT_CALENDAR = 'INIT_CALENDAR';
export const NEXT_MONTH = 'NEXT_MONTH';
export const PREV_MONTH = 'PREV_MONTH';

export const MONTH_SELECTED = 'MONTH_SELECTED';
export const SELECT_DATE = 'SELECT_DATE';

export const RECEIVE_REMINDERS_SUCCESS = 'RECEIVE_REMINDERS_SUCCESS';
export const SAVE_REMINDER = 'SAVE_REMINDER';
export const REMOVE_REMINDER = 'REMOVE_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
